### ISSUE TITLE
不错，但是好像缺shaderx系列

### ISSUE THREAD

**Issue by chena1982** [miloyip/game-programmer#1]
还是说觉得年代比较久了，就不需要了？

**Comment by miloyip** [comment]
是觉得实在太老而且现在的参考价值太低。反而更老的 Graphics Gems 还有些算法可参考。

**Comment by chena1982** [comment]
哦，还有windows编程和debug的书好像没有。

**Comment by miloyip** [comment]
嗯。其实游戏开发（前端方面）一般不会需要很多平台相关知识。
或许工具开发需要用到一些 GUI 框架。
如果有推荐也可告诉我。

**Comment by chena1982** [comment]
windows核心编程(必读)，操作系统的一些事情还是需要知道的。
ui也需要，qt，wpf。游戏用的ui，cegui，Scaleform这些。
debug，软件调试(必读)，Windows高级调试。
还有mathematica，不过mathematica没有特别的书。

**Comment by miloyip** [comment]
Mathematica 有 《An Elementary Introduction to the Wolfram Language》。

**Comment by miloyip** [comment]
《Windows via C/C++ 5th Edition》 已经是 10 年前的了。这本我没读过。
