### ISSUE TITLE
《Mathematics for 3D Game Programming and Computer Graphics》的中文版封面有误

### ISSUE THREAD

**Issue by zackszhu** [miloyip/game-programmer#15]
目前（2016.12.18）中文版的书籍名称为《3D数学基础：图形与游戏开发》作者是Dunn Fletcher。而英文版推荐的是《Mathematics for 3D Game Programming and Computer Graphics》其作者为Eric Lengyel。
应更换为中文书籍《3D游戏与计算机图形学中的数学方法（第3版）》
![封面](https://images-cn.ssl-images-amazon.com/images/I/61UnZNFrV5L.jpg)

**Comment by miloyip** [comment]
Thank you for reporting.
