### ISSUE TITLE
中文版

### ISSUE THREAD

**Issue by miloyip** [miloyip/game-programmer#5]
一直有朋友反馈觉得需要中文版，想在此协调一下，看看有没有人愿意帮忙。

我的构想：

* 不希望完全另写一个 game-programmer.dot，这样不方便更新
* 用一个数据表表示有中文译本的著作，如 ISBN, zh-ISBN, zh-title 的 CSV 文件
* 译本的封面的图像文件用同名储存在 image-zh 目录
* 编写脚本，替代 game-programmer.dot 中有译本的记录（链接至豆瓣），文本替换（如标题），生成 game-programmer-zh.dot 及生成 pdf/svg/png/jpg 文件

请有兴趣的朋友参与讨论。

**Comment by tkchu** [comment]
正着手对应的CSV文件。格式为：
```
索引号,图片目录,书籍英文名称,亚马逊英文网站购买地址,书籍英文版豆瓣地址,书籍中文名,书籍中文版豆瓣地址
举例：
adventuresinminecraft,images/adventuresinminecraft.jpg,Adventures in Minecraft (2014),https://www.amazon.com/dp/111894691X/,https://book.douban.com/subject/26306104/,零基础学Minecraft编程,https://book.douban.com/subject/26613247/
```

中文版对应规则：
1. 根据豆瓣右侧的“这本书的其他版本” 选择英文版的对应版本。
2. 选择该英文版本的对应中文版中最新的版本。
3. 如果不满足，则选择英文版前一版本对应的中文版。
4. 若初版英文版亦无对应的中文版本，则使用中文缺省值：
5. 若英文版无对应豆瓣界面，使用英文缺省值，并向豆瓣报备。

```
缺少中文版本豆瓣界面举例：
scratchjr,images/scratchjr.jpg,The` Official ScratchJr Book (2015),https://www.amazon.com/dp/1593276710/,https://book.douban.com/subject/26808435/,未找到中文,No Chinese Version Found
缺少英文版本豆瓣界面举例：
codinggamesinscratch,images/codinggamesinscratch.jpg,Coding Games in Scratch (2015),https://www.amazon.com/dp/1465439358/,暂无豆瓣链接（已提交豆瓣官方处理）,未找到中文,No Chinese Version Found
```
目前进度（48/204）

**Comment by miloyip** [comment]
可以先讨论下⋯⋯
我建议不影响原有的 .dot，只是做一个 csv 去生成另一个 .dot。
那么只需要 ISBN, zh-ISBN, zh-title。
URL 应该可用 ISBN 生成的，如amazon 的都是直接 ISBN，豆瓣要用 API。

**Comment by tkchu** [comment]
en.dot -> zh-cn.dot有两种方案：
1. 使用模板语言，各种语言版本都是对模板的填充。
2. 使用字符串匹配替换，使用en.dot作为模板，写脚本替换。

[豆瓣的API](https://developers.douban.com/wiki/?title=book_v2)，可使用其根据ISBN获得书籍情况。
问题有：
1. 豆瓣书籍不全，部分书籍英文版亦无页面。（可特判，然后再向豆瓣提出增加界面）
2. 缺少根据英文版查找对应中文版的API。
3. 我已经按之前说的格式把书籍对应的CSV做完了……

不过我认同使用英文版ISBN对应中文版ISBN的方案，方便后面的维护。
我先把之前格式的csv和爬下来对应的图片pull过来，可以根据它来爬取ISBN。

**Comment by tkchu** [comment]
我同意，那么需要手动写csv文件，包含：
```
书籍标识,英文版书籍标题,英文版ISBN,中文版书籍标题,中文版ISBN
举例：
adventuresinminecraft, Adventures in Minecraft (2014),9781118946916, 零基础学Minecraft编程,9787115398970
```
然后再写一个脚本文件，接受en.dot和这个csv文件作为输入，输出一个zhcn.dot文件

另外，确认要使用豆瓣的url吗？因为豆瓣上的书籍信息有滞后和欠缺，一些新上架的书籍并没有相应的信息。
但直接指向亚马逊中国似乎有点像导购……

**Comment by miloyip** [comment]
Thank you very much @tkchu

**Comment by miloyip** [comment]
刚刚在想，能不能加入译本的日期？
