### ISSUE TITLE
Milo 大神！替墙内的文革小将向您道歉

### ISSUE THREAD

**Issue by hanayashiki** [miloyip/game-programmer#52]
由于墙内大量小粉红不辨是非，向深耕知乎多年分享技术的您不断进行人身攻击，这些人一大部分是无知网民+水军，给您造成了困扰，作为墙内人我做不了什么，只能希望您不和小粉红计较，做您自己。

**Comment by pajon2015** [comment]
对CCP已经到了容忍的极限了，想不反共都不行。

**Comment by SilentSherlock** [comment]
你们是刚出墙还是故意的，issue是这样用的吗，你们的支持完全可以在facebook，twitter上表达，没必要在项目上提issue，把无关的人引到GitHub上来

**Comment by fontomas** [comment]
你要道歉，你跪着磕十个响头拍个视频发给他不就好了吗。

**Comment by 547437352** [comment]
miloyip大神,崇拜您,深入一线,事必亲为,但是要爱护自己的身体,别冲的太靠前,免得警察伤害您

Miloyip God, adore you,Go to the front line and do anything by yourself,But take care of your body. Don't rush to the front,In case the police hurt you by mistake

**Comment by chongbaidashen** [comment]
miloyip大神,崇拜您,深入一线,事必亲为,但是要爱护自己的身体,别冲的太靠前,免得警察伤害您 

Miloyip God, adore you,Go to the front line and do anything by yourself,But take care of your body. Don't rush to the front,In case the police hurt you by mistake

**Comment by tinyvan** [comment]
生而为人,底线是要有的

**Comment by bot66** [comment]
？

**Comment by jackie1in** [comment]
？
