### ISSUE TITLE
Too many books to read in one lifetime

### ISSUE THREAD

**Issue by Monata** [miloyip/game-programmer#54]
Hi I came across this repo on Reddit and I simply think this is a false example for eager developers who wants to start. Just in the computer science block, there is CSAPP and CAAQA. Now I think CSAPP is enough of a challenge and it provides enough knowledge about computer architecture and in the computer graphics block there is a book specifically for physically-based rendering apart from the fundamentals of computer graphics. Now I don't think it's bad to learn about the fundamentals, I don't think it's necessary to master them if you're not planning on building a game engine itself. In fact, I don't think this whole path would suit most people since most independent developers use a game engine, and mastering that tool helps more to the developers. I might be wrong but I would hate to see people getting discouraged by this over-ambitious study path and give up where they could have created something if they were to follow a simpler and more focused path.

**Comment by maudzekod4000** [comment]
I think this is not the approach for "eager developer". It is for those who want to lay deep foundations and understanding in the matter.
I, for example, am a self-taught developer and do not have deep foundations in CS. This was fine 3-4 years into my career, but now (5-6 years into) I am starting to feel that I need that knowledge to propel my career further.
So I would approach game development in a different way - with more background and while at that stage I play a lot of games to get a better overview of the ecosystem and what games are interesting and so on...

**Comment by miloyip** [comment]
In the game industry, there are diffrent types of programmers/engineers. And of course not every book in the list is for every one. Also I try to show some recommended path and optional ones.

I agree that it may be an ideal or over-ambitious, but it is like a RPG that you may want to level up and select your path in the skill tree, which may spread over decades of "playtime". And not everyone can go through to the advanced levels. Game developers can also find different ways of improvements, e.g., develop mixed skills of artist side (becoming TA), game designer side (becoming TD), or even a generalist who can produce a whole game project by himself.

I started programming and game development in the young ages. Lack of sufficient background knowledge, I wasted quite some time in trial-and-errors and reading bits by bits randomly available at those times. I really hope some of the best books I could have read at suitable time in my life.

As mentioned in readme:
> The books shown in the WORK represent knowledge/skills that may/should be acquired by game programmers. There are other important ways of learning, such as practicing, courses, industrial/academic conferences/publications, etc.

You may need those knowledge in the career, or you may not. Your mileage may vary.
