### ISSUE TITLE
Suggestion for improvement

### ISSUE THREAD

**Issue by HurSungYun** [miloyip/game-programmer#6]
Hello. I'm deeply impressed with your study path and I am going to follow it.

However, I believe this path could be improved.

Contents related with concurrency are a bit weak.

[The Art of Multiprocessor Programming](https://www.amazon.com/Art-Multiprocessor-Programming-Revised-Reprint/dp/0123973376)

Adding this book in the curriculum would be great.

**Comment by multlurk** [comment]
Should I read "Compilers: Principles, Techniques, and Tools" and "The Pragmatic Programmer"?

**Comment by HurSungYun** [comment]
I think The Dragon Book should be read by game programmers and sorry but I don't know much about "The Pragmatic Programmer"

**Comment by ghost** [comment]
"c++ concurrency in action" is already in the list, which is at least as good as your suggestion, if not better (judging by the top comments on amazon).

**Comment by HurSungYun** [comment]
@avemilia fair point. closing thie issue
