### ISSUE TITLE
《Agile Software Development》 和 《Head First Design Patterns》可以对调一下

### ISSUE THREAD

**Issue by seasmiles** [miloyip/game-programmer#7]
《Head First Design Patterns》是类似入门的读物，国内有本《大话设计模式》比较接近。《Agile Software Development》相对更严肃和学术一些，从难度和深度上都远超过《Head First Design Patterns》。

**Comment by miloyip** [comment]
Agree.

**Comment by seasmiles** [comment]
修改以后:
refactoring -> codecomplete2 和 agilesoftwaredev -> designpatterns 箭头交叉了；
对应中文版headfirstdesignpatterns -> agilesoftwaredev的虚线缺失，并且该处的图水平翻转了。
